"""Constants for websocket message types."""

SCRAP_JOB_PENDING = "SCRAP_JOB_PENDING"
SCRAP_JOB_IN_PROGRESS = "SCRAP_JOB_IN_PROGRESS"
SCRAP_JOB_COMPLETED = "SCRAP_JOB_COMPLETED"
SCRAP_JOB_ERROR = "SCRAP_JOB_ERROR"
SCRAP_JOB_TERMINATED = "SCRAP_JOB_TERMINATED"
SCRAP_JOB_STOPPED = "SCRAP_JOB_STOPPED"
