export const SCRAP_JOB_PENDING = "SCRAP_JOB_PENDING";
export const SCRAP_JOB_IN_PROGRESS = "SCRAP_JOB_IN_PROGRESS";
export const SCRAP_JOB_COMPLETED = "SCRAP_JOB_COMPLETED";
export const SCRAP_JOB_ERROR = "SCRAP_JOB_ERROR";
export const SCRAP_JOB_TERMINATED = "SCRAP_JOB_TERMINATED";
export const SCRAP_JOB_STOPPED = "SCRAP_JOB_STOPPED";
export const SCRAP_JOB_LOG = "SCRAP_JOB_LOG";

export const SCRAP_CLIENT_PENDING = "SCRAP_CLIENT_PENDING";
export const SCRAP_CLIENT_IN_PROGRESS = "SCRAP_CLIENT_IN_PROGRESS";
export const SCRAP_CLIENT_COMPLETED = "SCRAP_CLIENT_COMPLETED";
export const SCRAP_CLIENT_ERROR = "SCRAP_CLIENT_ERROR";
export const SCRAP_CLIENT_TERMINATED = "SCRAP_CLIENT_TERMINATED";
export const SCRAP_CLIENT_STOPPED = "SCRAP_CLIENT_STOPPED";
export const SCRAP_CLIENT_LOG = "SCRAP_CLIENT_LOG";

export const BULK_JOB_APPLICATION_LOG = "BULK_JOB_APPLICATION_LOG";
export const BULK_JOB_APPLICATION_EMAIL_SEND_LOG =
  "BULK_JOB_APPLICATION_EMAIL_SEND_LOG";

export const CLIENT_EMAIL_VALIDATION_PROGRESS =
  "CLIENT_EMAIL_VALIDATION_PROGRESS";
export const CLIENT_EMAIL_VALIDATION_COMPLETED =
  "CLIENT_EMAIL_VALIDATION_COMPLETED";
export const CLIENT_EMAIL_VALIDATION_ERROR = "CLIENT_EMAIL_VALIDATION_ERROR";
