export const SCRAP_JOB_PENDING = "SCRAP_JOB_PENDING";
export const SCRAP_JOB_IN_PROGRESS = "SCRAP_JOB_IN_PROGRESS";
export const SCRAP_JOB_COMPLETED = "SCRAP_JOB_COMPLETED";
export const SCRAP_JOB_ERROR = "SCRAP_JOB_ERROR";
export const SCRAP_JOB_TERMINATED = "SCRAP_JOB_TERMINATED";
export const SCRAP_JOB_STOPPED = "SCRAP_JOB_STOPPED";
export const SCRAP_JOB_LOG = "SCRAP_JOB_LOG";
