"""Create career job table

Revision ID: 1cdb270c8a7d
Revises: 92ffc67e8766
Create Date: 2026-03-08 14:31:48.019409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1cdb270c8a7d'
down_revision: Union[str, None] = '92ffc67e8766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('job_site_id', sa.Integer(), nullable=False),
    sa.Column('scrap_job_id', sa.Integer(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('contact_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_site_id'], ['job_sites.id'], ),
    sa.ForeignKeyConstraint(['scrap_job_id'], ['scrap_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Run downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_jobs')
    # ### end Alembic commands ###
