"""Create scrap job table

Revision ID: 92ffc67e8766
Revises: ca8ae45ca339
Create Date: 2026-03-08 14:30:12.043209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92ffc67e8766'
down_revision: Union[str, None] = 'ca8ae45ca339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrap_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_site_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_site_id'], ['job_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Run downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrap_jobs')
    # ### end Alembic commands ###
