"""Create job site table

Revision ID: ca8ae45ca339
Revises: 4b57187c3396
Create Date: 2026-03-08 14:29:32.966710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca8ae45ca339'
down_revision: Union[str, None] = '4b57187c3396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('scrap_duration', sa.Integer(), nullable=False),
    sa.Column('last_scrapped', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Run downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_sites')
    # ### end Alembic commands ###
